# Generated by Django 4.2 on 2023-05-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_alter_courses_id_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
