# Generated by Django 4.2 on 2023-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_delete_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Конец курса'),
        ),
        migrations.AddField(
            model_name='courses',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Начало курса'),
        ),
    ]
